### ISSUE TITLE
Changing the release version from the drop down menu causes the default page to be loaded

### ISSUE THREAD

**Issue by azeey** [gazebo-web/gazebosim-web-frontend#18]
If I'm currently on https://gazebosim.org/docs/garden/install_ubuntu and I click the Fortress item from the drop down menu, https://gazebosim.org/docs/fortress gets loaded instead of what I expect https://gazebosim.org/docs/fortress/install_ubuntu.

**Comment by mabelzhang** [comment]
Implementation hint for anyone trying to fix this:

I THINK it happens on this line:
https://github.com/gazebo-web/gazebosim-web-frontend/blob/4da2478c9ed82db0ae0c3f21bb70627d6a7a91ea/src/app/doc/doc.component.ts#L261

It just goes to the default page of a new version.

To make it remember what page you're on, and go to that page in the new version, it’d be something like this pseudocode:
```
oldSubPage = currPage;
this.router.navigate([‘/docs’, newVersion, oldSubPage]);
```

I haven't figured out how to remember the current page (`oldSubPage` in the pseudocode).

**Comment by mabelzhang** [comment]
Oh it is very trivial, literally `oldSubPage` can just be `this.page.name`. Opening a PR.
