### ISSUE TITLE
Anchor links are not generated properly

### ISSUE THREAD

**Issue by scpeters** [gazebo-web/gazebosim-web-frontend#29]
I'm having an issue with how anchor links are presented on the following page in Google Chrome:

* https://gazebosim.org/docs/all/getstarted

The link on [line 42 of get_started.md](https://github.com/gazebosim/docs/blob/master/get_started.md?plain=1#L42) should generate a link that leads to https://gazebosim.org/docs/all/getstarted#macos, but it results in `<a href="docs/all/getstarted#" title="#macos">macOS section</a>`, which doesn't go to that anchor.

**Comment by azeey** [comment]
This is now fixed with the sphinx based site.
